### ISSUE TITLE
on join crashes server from this error

### ISSUE THREAD

**Issue by IAP3X-DEV** [BedrockServer/nReQuest#1]
erver thread/CRITICAL ReflectionException: "Class xenialdan\customui\event\UIDataReceiveEvent does not exist" (EXCEPTION) in "src/pocketmine/plugin/PluginManager" at line 740
27.01 16:58:48 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/PluginManager(740): ReflectionParameter->getClass()
27.01 16:58:48 [Server] Server thread/DEBUG #1 plugins/nReQuest-master/src/mcpepc/floaty/nrequest/nReQuest(50): pocketmine\plugin\PluginManager->registerEvents(mcpepc\floaty\nrequest\nReQuest object, mcpepc\floaty\nrequest\nReQuest object)
27.01 16:58:48 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginBase(123): mcpepc\floaty\nrequest\nReQuest->onEnable()
27.01 16:58:48 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(587): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
27.01 16:58:48 [Server] Server thread/DEBUG #4 src/pocketmine/Server(2003): pocketmine\plugin\PluginManager->enablePlugin(mcpepc\floaty\nrequest\nReQuest object)
27.01 16:58:48 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1989): pocketmine\Server->enablePlugin(mcpepc\floaty\nrequest\nReQuest object)
27.01 16:58:48 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1783): pocketmine\Server->enablePlugins(integer 1)
27.01 16:58:48 [Server] Server thread/DEBUG #7 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
27.01 16:58:48 [Server] Server thread/DEBUG #8 (1): require(string phar:///custom.phar/src/pocketmine/PocketMine.php)

**Comment by MCPE-PC** [comment]
Download it [here](https://poggit.pmmp.io/ci/BedrockServer/nReQuest/~).
And do not forget that the plugin development is in progress.

*****You must install Slapper, too.*****
